const WatchlistModel = require("../model/WatchlistModel");

const watchlist = [
  {
    symbol: "BINANCE:BTCUSDT",
    displayName: "BTC",
    type: "crypto",
    currentPrice: 66780,
    percent: 1.32,
    prevClose: 65907.47,
    isDown: false,
  },
  {
    symbol: "BINANCE:ETHUSDT",
    displayName: "ETH",
    type: "crypto",
    currentPrice: 3185,
    percent: -0.74,
    prevClose: 3208.76,
    isDown: true,
  },
  {
    symbol: "BINANCE:BNBUSDT",
    displayName: "BNB",
    type: "crypto",
    currentPrice: 575,
    percent: 0.58,
    prevClose: 571.68,
    isDown: false,
  },
  {
    symbol: "BINANCE:SOLUSDT",
    displayName: "SOL",
    type: "crypto",
    currentPrice: 148,
    percent: 2.05,
    prevClose: 145.03,
    isDown: false,
  },

  {
    symbol: "AAPL",
    displayName: "Apple",
    type: "stock",
    currentPrice: 254.9,
    percent: 0.52,
    prevClose: 253.58,
    isDown: false,
  },
  {
    symbol: "MSFT",
    displayName: "Microsoft",
    type: "stock",
    currentPrice: 421.8,
    percent: 0.41,
    prevClose: 420.07,
    isDown: false,
  },
  {
    symbol: "GOOGL",
    displayName: "Google (A)",
    type: "stock",
    currentPrice: 309.7,
    percent: -0.33,
    prevClose: 310.72,
    isDown: true,
  },
  {
    symbol: "NVDA",
    displayName: "NVIDIA",
    type: "stock",
    currentPrice: 184.2,
    percent: 1.12,
    prevClose: 182.17,
    isDown: false,
  },
  {
    symbol: "META",
    displayName: "Meta",
    type: "stock",
    currentPrice: 482.3,
    percent: -0.68,
    prevClose: 485.59,
    isDown: true,
  },
  {
    symbol: "AMZN",
    displayName: "Amazon",
    type: "stock",
    currentPrice: 179.6,
    percent: 0.72,
    prevClose: 178.32,
    isDown: false,
  },
  {
    symbol: "TSLA",
    displayName: "Tesla",
    type: "stock",
    currentPrice: 395.5,
    percent: -1.25,
    prevClose: 400.51,
    isDown: true,
  },
  {
    symbol: "AMD",
    displayName: "AMD",
    type: "stock",
    currentPrice: 198.1,
    percent: 1.05,
    prevClose: 196.04,
    isDown: false,
  },
  {
    symbol: "INTC",
    displayName: "Intel",
    type: "stock",
    currentPrice: 46.2,
    percent: -0.62,
    prevClose: 46.49,
    isDown: true,
  },

  {
    symbol: "JPM",
    displayName: "JPMorgan",
    type: "stock",
    currentPrice: 287.9,
    percent: 0.38,
    prevClose: 286.81,
    isDown: false,
  },
  {
    symbol: "BAC",
    displayName: "Bank of America",
    type: "stock",
    currentPrice: 38.4,
    percent: -0.45,
    prevClose: 38.57,
    isDown: true,
  },
  {
    symbol: "WFC",
    displayName: "Wells Fargo",
    type: "stock",
    currentPrice: 76.9,
    percent: 0.31,
    prevClose: 76.66,
    isDown: false,
  },
  {
    symbol: "GS",
    displayName: "Goldman Sachs",
    type: "stock",
    currentPrice: 412.2,
    percent: -0.55,
    prevClose: 414.49,
    isDown: true,
  },
  {
    symbol: "MS",
    displayName: "Morgan Stanley",
    type: "stock",
    currentPrice: 99.1,
    percent: 0.22,
    prevClose: 98.88,
    isDown: false,
  },
  {
    symbol: "C",
    displayName: "Citigroup",
    type: "stock",
    currentPrice: 108.4,
    percent: -0.36,
    prevClose: 108.79,
    isDown: true,
  },
  {
    symbol: "AXP",
    displayName: "American Express",
    type: "stock",
    currentPrice: 226.7,
    percent: 0.64,
    prevClose: 225.25,
    isDown: false,
  },
  {
    symbol: "BLK",
    displayName: "BlackRock",
    type: "stock",
    currentPrice: 808.5,
    percent: 0.42,
    prevClose: 805.11,
    isDown: false,
  },

  {
    symbol: "WMT",
    displayName: "Walmart",
    type: "stock",
    currentPrice: 166.2,
    percent: 0.28,
    prevClose: 165.74,
    isDown: false,
  },
  {
    symbol: "COST",
    displayName: "Costco",
    type: "stock",
    currentPrice: 718.3,
    percent: -0.52,
    prevClose: 722.06,
    isDown: true,
  },
  {
    symbol: "HD",
    displayName: "Home Depot",
    type: "stock",
    currentPrice: 377.4,
    percent: 0.75,
    prevClose: 374.59,
    isDown: false,
  },
  {
    symbol: "NKE",
    displayName: "Nike",
    type: "stock",
    currentPrice: 97.6,
    percent: -0.91,
    prevClose: 98.5,
    isDown: true,
  },
  {
    symbol: "MCD",
    displayName: "McDonald's",
    type: "stock",
    currentPrice: 286.7,
    percent: 0.37,
    prevClose: 285.64,
    isDown: false,
  },
  {
    symbol: "SBUX",
    displayName: "Starbucks",
    type: "stock",
    currentPrice: 101.9,
    percent: -0.48,
    prevClose: 102.39,
    isDown: true,
  },
  {
    symbol: "TGT",
    displayName: "Target",
    type: "stock",
    currentPrice: 143.2,
    percent: 0.33,
    prevClose: 142.73,
    isDown: false,
  },
  {
    symbol: "LOW",
    displayName: "Lowe's",
    type: "stock",
    currentPrice: 242.1,
    percent: 0.56,
    prevClose: 240.75,
    isDown: false,
  },

  {
    symbol: "JNJ",
    displayName: "Johnson & Johnson",
    type: "stock",
    currentPrice: 237.6,
    percent: -0.18,
    prevClose: 238.03,
    isDown: true,
  },
  {
    symbol: "PFE",
    displayName: "Pfizer",
    type: "stock",
    currentPrice: 32.8,
    percent: 0.24,
    prevClose: 32.72,
    isDown: false,
  },
  {
    symbol: "MRK",
    displayName: "Merck",
    type: "stock",
    currentPrice: 116.9,
    percent: 0.11,
    prevClose: 116.77,
    isDown: false,
  },
  {
    symbol: "ABBV",
    displayName: "AbbVie",
    type: "stock",
    currentPrice: 174.9,
    percent: -0.42,
    prevClose: 175.64,
    isDown: true,
  },
  {
    symbol: "LLY",
    displayName: "Eli Lilly",
    type: "stock",
    currentPrice: 931.5,
    percent: 1.15,
    prevClose: 920.88,
    isDown: false,
  },
  {
    symbol: "GILD",
    displayName: "Gilead",
    type: "stock",
    currentPrice: 81.7,
    percent: -0.31,
    prevClose: 81.96,
    isDown: true,
  },
  {
    symbol: "TMO",
    displayName: "Thermo Fisher",
    type: "stock",
    currentPrice: 562.9,
    percent: 0.48,
    prevClose: 560.22,
    isDown: false,
  },

  {
    symbol: "XOM",
    displayName: "ExxonMobil",
    type: "stock",
    currentPrice: 160.2,
    percent: 0.29,
    prevClose: 159.74,
    isDown: false,
  },
  {
    symbol: "CVX",
    displayName: "Chevron",
    type: "stock",
    currentPrice: 164.8,
    percent: -0.35,
    prevClose: 165.38,
    isDown: true,
  },
  {
    symbol: "BA",
    displayName: "Boeing",
    type: "stock",
    currentPrice: 199.9,
    percent: 0.52,
    prevClose: 198.86,
    isDown: false,
  },
  {
    symbol: "CAT",
    displayName: "Caterpillar",
    type: "stock",
    currentPrice: 318.7,
    percent: -0.72,
    prevClose: 321.02,
    isDown: true,
  },
  {
    symbol: "GE",
    displayName: "General Electric",
    type: "stock",
    currentPrice: 161.4,
    percent: 0.63,
    prevClose: 160.39,
    isDown: false,
  },
  {
    symbol: "HON",
    displayName: "Honeywell",
    type: "stock",
    currentPrice: 209.6,
    percent: -0.27,
    prevClose: 210.17,
    isDown: true,
  },
];

async function updateDB() {
  await WatchlistModel.insertMany(watchlist);
  console.log("done xxx");
}

module.exports = { updateDB };
